### ISSUE TITLE
Pseudo-code-review

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia-csharp-extension#2]
This seems to be a fairly new repository, but I came across some things and wanted to understand a bit better about it:

- https://github.com/theia-ide/theia-csharp-extension/blob/master/csharp/src/browser/csharp-contribution.ts#L26
   Aren't these some ruby extensions? Shouldn't we put `.cs` in there?

- https://github.com/theia-ide/theia-csharp-extension/blob/master/csharp/src/node/csharp-contribution.ts#L27
   Leftover?

- https://github.com/theia-ide/theia-csharp-extension/blob/master/csharp/src/browser/csharp-frontend-module.ts#L17
   `.toService()`

**Comment by svenefftinge** [comment]
Thanks for the feedback! Highly appreciated. 
Do you want to create a PR or should I?
